### ISSUE TITLE
GPIO pull in wrong direction?

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/gpio-music-box#10]
Looking at the code used in worksheet.md...
```python
for pin in sound_pins:
    GPIO.setup(pin, GPIO.IN, GPIO.PUD_DOWN)
    GPIO.add_event_detect(pin, GPIO.FALLING, play, 1000)
```
...and with the buttons connected between the GPIO pins and GND, then in theory the GPIO pins will *always* be low, and so the FALLING callback would never get triggered?!
However I suspect that it actually *does* work on a real Pi (I'm assuming somebody tested the worksheet) because the external 1.8 KOhm pullups on the I2C pins GPIO 2 and 3 are over-riding the weak 50 KOhm pulldowns inside the SoC. I believe if anybody then extended the project as suggested by adding extra buttons, then any button NOT connected to GPIOs 2 or 3 wouldn't work.

If I'm right, changing every occurrence of `GPIO.PUD_DOWN` in the worksheet to `GPIO.PUD_UP` should fix the problem?

**Comment by bennuttall** [comment]
Ah, sorry. I completely missed this issue - and it was valid. It was brought to my attention today and I fixed it in 38e150d2f0208b0a3e12de07110c5619b22f00ee. Thanks though!
