### ISSUE TITLE
Unable to invoke IDLE with sudo

### ISSUE THREAD

**Issue by DeeJay** [raspberrypilearning/gpio-music-box#14]
re: https://github.com/raspberrypilearning/gpio-music-box/blob/master/worksheet.md

Step 8: Open the Python file in IDLE with the command sudo idle musicbox.py &

IDLE is a tkinter (X-windows client) application. It cannot be invoked with sudo.

See https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=112536 for an end-user report of this issue.

**Comment by gbaman** [comment]
I have just verified this with a recent version of Raspbian and am not able to reproduce the reported issue by doing ```sudo idle musicbox.py &```.
It quite happily opens up IDLE without issue inside LXDE.
I have used this many times without ever coming across an issue.
The only reason this wouldn't work is if you hadn't started x (using ```startx```), although the guide does say in step one 
```Open a Terminal window from the desktop or application menu.```
So you need to have started LXDE to be able to do this.

As for the issues brought up in the thread, all commands preceding step 9 can only be entered into LXTerminal as you wouldn't have IDLE open at that point.

**Comment by bennuttall** [comment]
As @gbaman says, this is not an issue. `sudo idle &` works fine.

From the forum thread it looks like the user had difficulty following the instructions correctly.
