### ISSUE TITLE
New code using GPIO Zero

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/gpio-music-box#15]
When the time comes to update to use `gpiozero`, here's the code:

```python
from gpiozero import Button
import pygame.mixer
from pygame.mixer import Sound
from signal import pause

pygame.mixer.init()

sound_pins = {
    2: Sound("samples/drum_tom_mid_hard.wav"),
    3: Sound("samples/drum_cymbal_open.wav"),
}

buttons = [Button(pin) for pin in sound_pins]
for button in buttons:
    sound = sound_pins[button.pin]
    button.when_pressed = sound.play

pause()
```

[edited]

**Comment by waveform80** [comment]
If RPi-Distro/python-gpiozero#24 is accepted the code will actually look like this (not a huge difference, but still):

```python
from gpiozero import Button
import pygame.mixer
from pygame.mixer import Sound

pygame.mixer.init()

sound_pins = {
    2: Sound("samples/drum_tom_mid_hard.wav"),
    3: Sound("samples/drum_cymbal_open.wav"),
}

def play(btn):
    sound = sound_pins[btn.pin]
    print("playing note from pin %s" % btn.pin)
    sound.play()

buttons = []
for pin in sound_pins:
    button = Button(pin)
    button.when_pressed = play
    buttons.append(button)

print("ready")

while True:
    pass # improve this
```

Or you could write it like this:

```python
from gpiozero import Button
import pygame.mixer
from pygame.mixer import Sound

pygame.mixer.init()

sound_pins = {
    2: Sound("samples/drum_tom_mid_hard.wav").play,
    3: Sound("samples/drum_cymbal_open.wav").play,
}

buttons = [Button(pin) for pin in sound_pins]
for button in buttons:
    button.when_pressed = sound_pins[button.pin]

print("ready")

while True:
    pass # improve this
```

The only reason the `buttons` list is declared in the above examples is to keep the button instances "alive" after construction (potentially there's no references left to anything but the last object so the garbage collector is free to collect them - even if it doesn't in practice it's still a good idea to keep a reference around to them).

**Comment by bennuttall** [comment]
Hmm. I can't decide which method I prefer. The for loop in the first one is nice and easy to understand but building up a list and never using it doesn't make sense.

The second one makes sense but introduces list comprehension, which I'm not totally against using in more advanced resources (and this example is fine). I think the second one wins :)

Having said that, I don't like the fact the dict contains the function references rather than the Sound objects. How about:

```python
sound_pins = {
    2: Sound("samples/drum_tom_mid_hard.wav"),
    3: Sound("samples/drum_cymbal_open.wav"),
}

buttons = [Button(pin) for pin in sound_pins]
for button in buttons:
    sound = sound_pins[button.pin]
    button.when_pressed = sound.play
```

**Comment by waveform80** [comment]
Well, it's not that you're never using the list in the first one. You're using it to keep references to the buttons alive (rather important in a garbage collected language). That said, it's certainly not an obvious usage and I wouldn't expect kids or newbies to necessarily understand it.

Personally, I rather like the function references in the second simply because it demonstrates that methods and functions are first order objects which can be passed around like any other value. But still, you're right: it probably isn't kid / newbie friendly, so your version is a good compromise. Keeps all the objects alive, and still manages to sneak a list-comprehension in to keep everyone their toes ;)
