### ISSUE TITLE
Sonic Pi samples are no longer .wav

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/gpio-music-box#17]
I've just realised, while testing for #16, that the Sonic Pi sample files are no longer .wav files, and are .flac. Pygame cannot play these files, so the resource no longer works as is.

Can anyone suggest an alternative location in Raspbian where wav file samples can be found, or a way of converting them, or a way of playing them with pygame.

Ideally we would avoid having to download files from the internet as this makes it difficult to prepare for.

FYI @MarcScott @samaaron

**Comment by cyriel** [comment]
1. install flac using "sudo apt-get install flac"
2. In the folder of samples that you copied, run the command "flac -d *.flac"
  - This converts all flac files in the folder into a wav file.
  - To make this easier, prepare it once on a pi, and copy the files off on a flash drive for distribution.
3. Continue using this code as usual as usual.

NOTE1: Steps 1 and 2 require the use of the terminal.
NOTE2: When running commands, do not include the quotes

**Comment by bennuttall** [comment]
The new [GPIO Zero book](https://www.raspberrypi.org/magpi/gpio-zero-essentials/) uses Scratch sample sounds instead of Sonic Pi, which I think is a good way of resolving this issue.

@MarcScott do you mind making this change? The resource is currently broken because of this issue.
