### ISSUE TITLE
Error in "wire up first button" and "add second button..."

### ISSUE THREAD

**Issue by yjvben** [raspberrypilearning/gpio-music-box#5]
title : wire up first button
fritzing picture after 4. shows blue line connecting to pin 5 and 7, should be pin 3 and 5.
title : add second button ...
fritzing picture after 1. , same mistake as in first button picture.

maybe use other gnd line to leave space for the blue lines. 
source :  gpio-connect-button2.png

**Comment by bennuttall** [comment]
Ah, yes. You're right. I'll fix them when I get chance.

Thanks

**Comment by bennuttall** [comment]
I've fixed the images now. @yjvben @shday does it look right to you?

+ duplicate issue #6

**Comment by shday** [comment]
Yeah, now it is consistent with the others... buttons are all connected to ground.

**Comment by yjvben** [comment]
Yes, thank you 

----- Oorspronkelijk bericht -----

Van: "Ben Nuttall" <notifications@github.com> 
Aan: "raspberrypilearning/gpio-music-box" <gpio-music-box@noreply.github.com> 
Cc: "yjvben" <Befour@bigfoot.com> 
Verzonden: Dinsdag 6 januari 2015 16:18:25 
Onderwerp: Re: [gpio-music-box] Error in "wire up first button" and "add second button..." (#5) 



I've fixed the images now. @yjvben @shday does it look right to you? 

    * duplicate issue #6
